# Generated by Django 5.0.6 on 2024-05-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
