# Generated by Django 5.0.6 on 2024-06-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_taskstatus_alter_project_name_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
