# Generated by Django 5.0.6 on 2024-06-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_taskstatus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='deadline',
        ),
    ]
