# Generated by Django 5.0.6 on 2024-06-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_subtask_submited_by_task_submited_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='assigned',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='task_status',
        ),
    ]
