# Generated by Django 5.0.6 on 2024-06-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_rename_assigned_subtask_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='submited_by',
            new_name='user',
        ),
    ]
