# Generated by Django 5.0.6 on 2024-06-01 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_rename_submited_by_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='member_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.membertype'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.taskstatus'),
        ),
    ]
