# Generated by Django 5.0.6 on 2024-06-01 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_task_member_type_alter_task_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='subtask_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.taskstatus'),
        ),
        migrations.AlterField(
            model_name='task',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.member'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.taskstatus'),
        ),
    ]
